INSERT INTO portal.user 
(USER_ID, CREATED_AT, SHARD_KEY, UPDATED_AT, EMAIL_ID, USERNAME, CREATED_BY, UPDATED_BY, USER_TYPE) VALUES 
(1, now(), null, now(), 'akhtar.azaz@live.com', 'Pass@123', null, null, 1);

INSERT INTO portal.password 
(PASSWORD_ID, CREATED_AT, SHARD_KEY, UPDATED_AT, PASSWORD_HASH, PASSWORD_STATUS, CREATED_BY, UPDATED_BY, USER_ID) VALUES 
(1, now(), null, now(), '21232f297a57a5a743894a0e4a801fc3', 1, 1, 1, 1);